name: Build and Release Executables

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write   # allow creating/updating releases

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --verbose pyqt5 fpdf2 tabulate pyinstaller pywin32
          
      - name: Build CLI Executable
        run: pyinstaller --onedir --console --name "ScaleReportCLI" --add-data "assets/fonts;assets/fonts" --add-data "assets/imgs;assets/imgs" --icon="assets/imgs/favicon.ico" __mainCLI__.py
      - name: Build GUI Executable
        run: |
          pyinstaller --onedir --windowed --name "ScaleReportGUI" --add-data "assets/fonts;assets/fonts" --add-data "assets/imgs;assets/imgs" --icon="assets/imgs/favicon.ico" __mainQtGUI__.py

      - name: Rename Artifacts with OS Suffix
        run: |
          OS_NAME=${{ matrix.os }}
          case "$OS_NAME" in
            ubuntu-*) SUFFIX="ubuntu" ;;
            macos-*) SUFFIX="macos" ;;
            windows-*) SUFFIX="windows" ;;
          esac

          mkdir release
          if [[ "$OS_NAME" == windows-* ]]; then
            mv dist/ScaleReportCLI release/ScaleReportCLI-$SUFFIX
            mv dist/ScaleReportGUI release/ScaleReportGUI-$SUFFIX
          else
            mv dist/ScaleReportCLI release/ScaleReportCLI-$SUFFIX
            mv dist/ScaleReportGUI release/ScaleReportGUI-$SUFFIX
          fi
        shell: bash



      - name: Upload new assets to "executables" release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: executables
          name: "Release Executables"
          files: release/*
          overwrite: true   # replaces existing assets by name
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
